/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.opensearch.analysis.thai.engine;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

/**
 * Loads the bundled {@code bound-morphemes.txt} word list: dictionary entries that a
 * gold-standard corpus (LST20, train+eval split) shows are almost never used as a
 * standalone word (occurring alone at most 4 times in ~2.6M tokens) but are frequently
 * a prefix or suffix fragment of longer real words (e.g. {@code สุ}, {@code ไชย} — both
 * fragments of the surname {@code สุรไชย}, which the base Viterbi dictionary otherwise
 * wrongly splits into {@code สุ|ร|ไชย}). Generated by {@code scripts/extract-bound-morphemes.py}.
 *
 * <p>Used only when a tokenizer explicitly opts in via {@code filter_bound_morphemes: true}
 * (see {@link ThaiTrie#exclude(Set)}); default tokenizer behavior is unaffected.
 *
 * <p>Validated on the LST20 test split (held out from the word list itself): enabling the
 * filter improves boundary-level F1 from 93.19% to 93.25% (net +274 correct boundaries,
 * 798 fixed vs. 524 newly wrong, across 483 documents / ~785K characters) with no observed
 * harm to ordinary compound-word recognition.
 */
public final class BoundMorphemeSets {

    private static final String RESOURCE = "/org/opensearch/analysis/thai/bound-morphemes.txt";

    private static final Set<String> WORDS = load();

    private BoundMorphemeSets() {}

    /** Returns the bundled candidate set (immutable, shared, safe to read concurrently). */
    public static Set<String> get() {
        return WORDS;
    }

    private static Set<String> load() {
        Set<String> words = new HashSet<>();
        try (InputStream is = BoundMorphemeSets.class.getResourceAsStream(RESOURCE)) {
            if (is == null) return Set.of();
            BufferedReader br = new BufferedReader(new InputStreamReader(is, StandardCharsets.UTF_8));
            String line;
            while ((line = br.readLine()) != null) {
                line = line.strip();
                if (!line.isEmpty() && !line.startsWith("#")) words.add(line);
            }
        } catch (IOException e) {
            // Missing resource: behave as if the list were empty.
        }
        return Collections.unmodifiableSet(words);
    }
}
